### ISSUE TITLE
ImportError: cannot import name 'RenderGroup' from 'rich.console'

### ISSUE THREAD

**Issue by raananelefant** [gmso/recipys#3]
recipys -h                                        
Traceback (most recent call last):   
File "/data/data/com.termux/files/usr/bin/recipys", line 5, in <module>     from recipys.App import main   File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/recipys/App.py", line 4, in <module>     from recipys.ConsolePrinter import ConsolePrinter
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/recipys/ConsolePrinter.py", line 7, in <module>     from rich.console import RenderGroup              ImportError: cannot import name 'RenderGroup' from 'rich.console' (/data/data/com.termux/files/usr/lib/python3.7/site-packages/rich/console.py)

**Comment by raananelefant** [comment]
pip3.7 show rich
Name: rich
Version: 13.7.1                                       Summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
Home-page: https://github.com/Textualize/rich
Author: Will McGugan
Author-email: willmcgugan@gmail.com
License: MIT                                          Location: /data/data/com.termux/files/usr/lib/python3.7/site-packages
Requires: markdown-it-py, pygments, typing-extensions Required-by: recipys

**Comment by raananelefant** [comment]
Tested in python 3.7, 3.9 and 3.11

**Comment by raananelefant** [comment]
Fix:

Replace all instances of RenderGroup with Group in /data/data/com.termux/files/usr/lib/python3.7/site-packages/recipys/ConsolePrinter.py
